# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_bot', '0003_auto_20171203_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='moderator_expire',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
